# Generated by Django 5.2.3 on 2025-06-29 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('thunder', models.IntegerField(default=0)),
                ('pest_count', models.IntegerField(default=0)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='Online', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
