# Generated by Django 5.2.3 on 2025-06-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinate', null=True),
        ),
    ]
