# Generated by Django 5.2.3 on 2025-06-30 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sensordata_latitude_sensordata_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_percent', models.FloatField(blank=True, help_text='CPU usage percentage', null=True)),
                ('ram_percent', models.FloatField(blank=True, help_text='RAM usage percentage', null=True)),
                ('ram_used_gb', models.FloatField(blank=True, help_text='RAM used in GB', null=True)),
                ('ram_total_gb', models.FloatField(blank=True, help_text='Total RAM in GB', null=True)),
                ('storage_percent', models.FloatField(blank=True, help_text='Storage usage percentage', null=True)),
                ('storage_used_gb', models.FloatField(blank=True, help_text='Storage used in GB', null=True)),
                ('storage_total_gb', models.FloatField(blank=True, help_text='Total storage in GB', null=True)),
                ('network_sent_mb', models.FloatField(blank=True, help_text='Network bytes sent in MB', null=True)),
                ('network_recv_mb', models.FloatField(blank=True, help_text='Network bytes received in MB', null=True)),
                ('load_1min', models.FloatField(blank=True, help_text='1-minute load average', null=True)),
                ('load_5min', models.FloatField(blank=True, help_text='5-minute load average', null=True)),
                ('load_15min', models.FloatField(blank=True, help_text='15-minute load average', null=True)),
                ('status', models.CharField(default='Online', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='sensordata',
            unique_together={('timestamp', 'temperature', 'humidity', 'rainfall', 'thunder', 'pest_count')},
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['-timestamp'], name='dashboard_s_timesta_148537_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['status'], name='dashboard_s_status_7e67a0_idx'),
        ),
        migrations.AddIndex(
            model_name='systemdata',
            index=models.Index(fields=['-timestamp'], name='dashboard_s_timesta_2576a3_idx'),
        ),
        migrations.AddIndex(
            model_name='systemdata',
            index=models.Index(fields=['status'], name='dashboard_s_status_eb4bf2_idx'),
        ),
    ]
