# Generated by Django 5.2.3 on 2025-07-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_system_data_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdata',
            name='cpu_temp',
            field=models.FloatField(blank=True, help_text='CPU temperature in Celsius', null=True),
        ),
    ]
