# Generated by Django 5.2.3 on 2025-07-05 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_systemdata_cpu_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_detections', models.IntegerField(default=0, help_text='Total number of pests detected')),
                ('class_counts', models.JSONField(default=dict, help_text='Count of each pest class detected')),
                ('detection_details', models.JSONField(default=list, help_text='Detailed detection information')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude where detection occurred', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude where detection occurred', null=True)),
                ('status', models.CharField(default='Completed', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='dashboard_d_timesta_d28093_idx'), models.Index(fields=['total_detections'], name='dashboard_d_total_d_c6b560_idx'), models.Index(fields=['status'], name='dashboard_d_status_c1adc7_idx')],
            },
        ),
    ]
