# Generated by Django 5.2.3 on 2025-07-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_detectiondata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='battery_level',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='cpu_usage',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='pest_types',
            field=models.JSONField(default=dict, help_text='Count of each pest type detected'),
        ),
    ]
