# Generated by Django 5.2.3 on 2025-07-06 05:15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_add_pest_type_to_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='battery_level',
            field=models.FloatField(blank=True, help_text='Battery level percentage', null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='cpu_usage',
            field=models.FloatField(blank=True, help_text='CPU usage percentage', null=True),
        ),
    ] 