# Generated by Django 5.2.3 on 2025-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_add_battery_cpu_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='battery_level',
        ),
        migrations.AddField(
            model_name='systemdata',
            name='battery_level',
            field=models.FloatField(blank=True, help_text='Battery level percentage', null=True),
        ),
    ]
