# Generated by Django 5.2.3 on 2025-08-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_move_battery_level_to_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectiondata',
            name='detection_details',
        ),
        migrations.AddField(
            model_name='detectiondata',
            name='growth_stage',
            field=models.CharField(default='Vegetatif', help_text='Rice paddy growth stage', max_length=50),
        ),
        migrations.AddIndex(
            model_name='detectiondata',
            index=models.Index(fields=['growth_stage'], name='dashboard_d_growth__ceb986_idx'),
        ),
    ]
