# Generated by Django 5.2.3 on 2025-08-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_add_growth_stage_to_detection_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectiondata',
            name='image_path',
            field=models.CharField(blank=True, help_text='Path to the detection image', max_length=255, null=True),
        ),
    ] 